### PR TITLE
fix: SocialConnect link in sidebar

### PR DESCRIPTION
**Pull request by therealharpaljadeja**

### CODE REVIEW

**Review by GigaHierz — CHANGES_REQUESTED** [review]
the old link leads to : https://github.com/celo-org/SocialConnect and the new link leads to https://github.com/celo-org/Social-Connect

1. add a description to the PR, why the link has been updated
2. remove unused/ duplicated repositories

**Comment by therealharpaljadeja** [comment]
> the old link leads to : https://github.com/celo-org/SocialConnect and the new link leads to https://github.com/celo-org/Social-Connect
> 
> 1. add a description to the PR, why the link has been updated
> 2. remove unused/ duplicated repositories

1 - @arthurgousset any context on why the repo was migrated to a new repo?
2 - which unused repositories? @GigaHierz

**Comment by GigaHierz** [comment]
https://github.com/celo-org/SocialConnect is archived so IO

**Review by GigaHierz — APPROVED** [review]

**Comment by arthurgousset** [comment]
> 1 - @arthurgousset any context on why the repo was migrated to a new repo? 2 - which unused repositories? @GigaHierz

Yes, the idea was to migrate ODIS and the smart contracts from [celo-org/celo-monorepo](https://github.com/celo-org/celo-monorepo/) to [celo-org/socialconnect](https://github.com/celo-org/socialconnect). 

But the goal was to include the **git commit history** from [celo-org/celo-monorepo](https://github.com/celo-org/celo-monorepo/) for ODIS and smart contract changes, and unfortunately you can only do that in a new repository with no git commit history. [celo-org/socialconnect](https://github.com/celo-org/socialconnect) already had a git history because of the demos we added, so we couldn't use that. We decided to create a brand-new repo without git history [celo-org/social-connect](https://github.com/celo-org/social-connect), migrate ODIS and the smart contracts including their git history, and add the demos/README after that.

**Pull request merged**
