### PR TITLE
tutorial for Hackathon: Celo Playgrounds: A Celebration of Diversity

### PR DESCRIPTION
**Pull request by lucasespinosa28**
my idea was to write a unique tutorial, the tutorial is not very complex, my idea was to show new ways to use EVM
the tutorial show how to create native android app using C# and how to use Nethereum to read smart contracts in celo network

### CODE REVIEW

**Review by lucasespinosa28 — COMMENTED** [review]
fixed error

**Review by lucasespinosa28 — COMMENTED** [review]
fix markdown tagas

**Review by lucasespinosa28 — COMMENTED** [review]
new name without #

**Comment by nestorbonilla** [comment]
LGTM! Thanks for the contribution! Looking forward to continuing the conversation on Discord.

**Review by nestorbonilla — APPROVED** [review]
LGTM! Thanks for the contribution! Looking forward to continuing the conversation on Discord.

**Pull request merged**
