### PR TITLE
Update CLI docs script

### PR DESCRIPTION
**Pull request by arthurgousset**
## Description

This PR: 
1. updates the docs path to match the changes made the `celo-org/developer-tooling` in this PR: https://github.com/celo-org/developer-tooling/pull/238

## Related

- Related https://github.com/celo-org/developer-tooling/pull/238
- Fixes https://github.com/celo-org/developer-tooling/issues/206 (by product of PR)

## Tested

Yes, running `yarn install` successful ran the `postinstall` hook, and fetched the latest commit from the `celo-org/developer-tooling` repp (see https://github.com/celo-org/docs/pull/1312/commits/eabaa2f4c0dd27aaa78b64d6db10c8fc8abb5888).

### CODE REVIEW

**Comment by arthurgousset** [comment]
At the moment, it looks like the script ([`scripts/copy-generated-docs.sh`](https://github.com/celo-org/docs/blob/5d31a997339af50ab210eed4ca1787e4037709fb/scripts/copy-generated-docs.sh)), which is called as a postinstall hook, doesn't fetch the latest commit from the `celo-org/developer-tooling` repo. 

For example:

```sh
$ yarn

# ...
$ ./scripts/copy-generated-docs.sh
Submodule 'submodules/developer-tooling' (https://github.com/celo-org/developer-tooling.git) registered for path 'submodules/developer-tooling'
Cloning into '/Users/arthur/Documents/celo-org/docs/submodules/developer-tooling'...
Submodule path 'submodules/developer-tooling': checked out 'cdba30e76e342949cc554ba5b6c1f2f9b6f7ace5'
cp: ./submodules/developer-tooling/docs/command-line-interface/*: No such file or directory
#...
```

It looks like it fetches this commit: https://github.com/celo-org/developer-tooling/commit/cdba30e76e342949cc554ba5b6c1f2f9b6f7ace5 (see shell output above), which is from a PR in Jan 2024:
- https://github.com/celo-org/developer-tooling/pull/104

**Comment by arthurgousset** [comment]
> At the moment, it looks like the script ([`scripts/copy-generated-docs.sh`](https://github.com/celo-org/docs/blob/5d31a997339af50ab210eed4ca1787e4037709fb/scripts/copy-generated-docs.sh)), which is called as a postinstall hook, doesn't fetch the latest commit from the `celo-org/developer-tooling` repo.
> 
> For example:
> 
> ```shell
> $ yarn
> 
> # ...
> $ ./scripts/copy-generated-docs.sh
> Submodule 'submodules/developer-tooling' (https://github.com/celo-org/developer-tooling.git) registered for path 'submodules/developer-tooling'
> Cloning into '/Users/arthur/Documents/celo-org/docs/submodules/developer-tooling'...
> Submodule path 'submodules/developer-tooling': checked out 'cdba30e76e342949cc554ba5b6c1f2f9b6f7ace5'
> cp: ./submodules/developer-tooling/docs/command-line-interface/*: No such file or directory
> #...
> ```
> 
> It looks like it fetches this commit: [celo-org/developer-tooling@cdba30e](https://github.com/celo-org/developer-tooling/commit/cdba30e76e342949cc554ba5b6c1f2f9b6f7ace5) (see shell output above), which is from a PR in Jan 2024:
> 
> * [Merge remote-tracking branch 'origin/master' into ci/docs-generation developer-tooling#104](https://github.com/celo-org/developer-tooling/pull/104)
> 
> Naturally, the script fails, becaus I change the docs file path in this PR:
> 
> ```shell
> cp: ./submodules/developer-tooling/docs/command-line-interface/*: No such file or directory
> ```

This is fixed in https://github.com/celo-org/docs/pull/1312/commits/6f5e22ae8597e87702b970d0c3f9e28d4e063ccd.

**Comment by arthurgousset** [comment]
Just paired with @nicolasbrugneaux, and I learnt that the script shouldn't pull the latest changes from `master` in `celo-org/developer-tooling`. Instead, we want to always have the commit of the latest release on `celo-org/developer-tooling`. Otherwise, the docs repo might be ahead of released features.

There is a workflow in the `celo-org/developer-tooling` repo ([`open-docs-pr.yml`](https://github.com/celo-org/developer-tooling/blob/master/.github/workflows/open-docs-pr.yml)) that opens a PR in the docs repo every time a new release is made to update the commit.

For example: 
- https://github.com/celo-org/docs/pull/1278

**Comment by arthurgousset** [comment]
Because we are about to do a CLI release, we agreed to keep the docs slightly ahead of the release: 
- https://github.com/celo-org/developer-tooling/pull/213

That means when the release is made, the automatic PR shouldn't make any docs changes. 
But any future releases will update the docs as expected.

**Review by viral-sangani — APPROVED** [review]

**Pull request merged**
