### PR TITLE
add graph post

### PR DESCRIPTION
**Pull request by critesjosh**

### CODE REVIEW

**Comment by ericnakagawa** [comment]
Digging this tutorial!
Some feedback:
+ I think there needs to be a bit more information around how to run the Observable HQ code to interact.

For the blog, we should make a link to it more prominent somewhere to top of nav, and landing page 
Also, the blog index page should show a paragraph or so of content from the post instead of one line. Could also hint with more information like how many words, or estimated reading time (like Medium).

**Comment by critesjosh** [comment]
Thanks @ericnakagawa. I added a link to the blog in the navbar, increased the amount of text that is displayed on the post index page and added estimated reading time.

I also added a post that explains more about observable.

**Comment by joenyzio** [comment]
LGTM! Here are a few things you can look out for if you'd like to add any extra details. 

- Add a beginning paragraph stating the benefits of using the Graph with Celo and the outcomes of the post 
- Show all referenced and implied code within the blog post (ex. git clone, Hello World smart contract)
- Provide resources and tips to help understand Graph commands and terminology as they are used

**Review by joenyzio — APPROVED** [review]

**Comment by joenyzio** [comment]
Approved for whenever you'd like to merge. Feedback is only suggestions.

**Comment by critesjosh** [comment]
thanks for the feedback @joenyzio, i updated the post to include your suggestions.

**Pull request merged**
