### PR TITLE
+Empathy For the people

### PR DESCRIPTION
**Pull request by APrimaveraV**
+Empathy'S Comunities 🤞👾🤞

### CODE REVIEW

**Comment by critesjosh** [comment]
The url you added is for binance. Is this intentional?

**Comment by APrimaveraV** [comment]
Hi from dominican Repúblic sr

Can You give me more orientations abouth for make My request in corrects
ways...?

Atte Richard Liria Nuñez From Liria Productions & +Empathy'S
Comunities...🙌🇩🇴🙌

**Comment by critesjosh** [comment]
sure, it depends on what you are trying to do. what are you trying to do?

**Comment by critesjosh** [comment]
Do you have a website? Are you building on Celo?

**Comment by critesjosh** [comment]
Of course, I'm happy to help. I will be happy to help you add your project to the docs when you have a website and start building on Celo. Before then I don't think it makes sense to add your project to the docs.

**Comment by APrimaveraV** [comment]
Hi againg from Dominican Republic sr...✌🏼🇩🇴✌🏾

Sorry for delay and thanks for the friendlys atentions whit people learning like me...!! Can we use other ways for introduce myself I'm really new in git hub and I need learn about use correctly to sr...!!

**Comment by nestorbonilla** [comment]
No updates were received. Please, feel free to open it with more information.

**Comment by APrimaveraV** [comment]
Hi again from the Dominican Republic Guys, and really sorry for delay

**Pull request closed without merging**
