### PR TITLE
Jovan Mwesigwa - Sage - Build a Decentralized Parking Ticket Payments DApp on Celo

### PR DESCRIPTION
**Pull request by JovanMwesigwa**
### Thanks for submitting this tutorial for Celo Sage

Before you hit "Create Pull Request", make sure you have read the [Tutorial Contribution Guidelines](https://docs.celo.org/community/celo-sage/contribution-guidelines) and reviewed the [Sample Tutorial Structure](https://docs.celo.org/community/celo-sage/tutorial-structure).

Please confirm the following before submitting your tutorial for review -

- [x] My tutorial follows the [Tutorial Contribution Guidelines](https://docs.celo.org/community/celo-sage/contribution-guidelines).
- [x] The title of the Pull Request matches the title of my tutorial.
- [x] I've followed the tutorial template structure.
- [x] I've proofread the tutorial for spelling and grammar mistakes.
- [x] I've thoroughly explained the code, with inline code comments and text explanations.
- [x] I've run a linter & prettifier to format my code blocks.
- [x] I've run the tutorial to test it and the code works.

> NOTE: We cannot review your Pull Request if it does not meet the standard outlined above.
> Reviewers - @joenyzio & @viral-sangani

### CODE REVIEW

**Review by bobeu — COMMENTED** [review]
Please fix the issues I highlighted below.

- There is the repetition of words.
- Images are not displaying.
- The title of the '.md' file does not tally with the proposed article.
- Change "You can clone the client repo [here](https://github.com/JovanMwesigwa/celo-parking-ticketing-dapp) and connect it to your contract address if you want to test your app on the front end." to "You can clone the client repo [here](https://github.com/JovanMwesigwa/celo-parking-ticketing-dapp) and connect it to your contract address if you want to test your app on the frontend."
- 

ch1

**Comment by viral-sangani** [comment]
@JovanMwesigwa Instead of using ‘ ’ these tags, please use backtick (`) everywhere in your article.
backtick is used to highlight the code, or directory name.

**Comment by viral-sangani** [comment]
What's the use of this file? - `src/data-tutorials/showcase/intermediate/Thumbs.db`

Please remove it.

**Comment by JovanMwesigwa** [comment]
> src/data-tutorials/showcase/intermediate/Thumbs.db

I've checked everywhere for this file, I can't find it anywhere in my commits even locally. I didn't add it anywhere

**Review by viral-sangani — APPROVED** [review]

**Pull request merged**
