### PR TITLE
[Peter Latona] - Sage - Unlocking the Power of Blockchain, Nfts, and Cryptography

### PR DESCRIPTION
**Pull request by SasaniEldis**
### Thanks for submitting this tutorial for Celo Sage

Before you hit "Create Pull Request", make sure you have read the [Tutorial Contribution Guidelines](https://docs.celo.org/community/celo-sage/contribution-guidelines) and reviewed the [Sample Tutorial Structure](https://docs.celo.org/community/celo-sage/tutorial-structure).

Please confirm the following before submitting your tutorial for review -

- [x] My tutorial follows the [Tutorial Contribution Guidelines](https://docs.celo.org/community/celo-sage/contribution-guidelines).
- [x] The title of the Pull Request matches the title of my tutorial.
- [x] I've followed the tutorial template structure.
- [x] I've proofread the tutorial for spelling and grammar mistakes.
- [x] I've thoroughly explained the code, with inline code comments and text explanations.
- [x] I've run a linter & prettifier to format my code blocks.
- [x] I've run the tutorial to test it and the code works.

> NOTE: We cannot review your Pull Request if it does not meet the standard outlined above.
> Reviewers - @joenyzio & @viral-sangani

### CODE REVIEW

**Review by Ishanpathak1 — COMMENTED** [review]
Will be moving this to publish

**Review by Ishanpathak1 — COMMENTED** [review]
Hey, just a change, I think the spaces in between the name of the images will create a problem while reading this markdown file, so can you change the names in a way it is not having the spaces and also , make sure you write that name of the image in the makrdown file  too

**Comment by SasaniEldis** [comment]
"Hey, just a change, I think the spaces in between the name of the images will create a problem while reading this markdown file, so can you change the names in a way it is not having the spaces and also , make sure you write that name of the image in the markdown file too"


...Thanks, I have made the changes...

**Review by viral-sangani — APPROVED** [review]

**Comment by developerkunal** [comment]
@viral-sangani  Have you not merged this yet but its already in done section of celo board?

**Comment by SasaniEldis** [comment]
Hi, @viral-sangani @joenyzio please help check if this has been merged. I saw it in the done card before I moved back to publish.

**Pull request merged**
