### PR TITLE
Celo Sage Hompage

### PR DESCRIPTION
**Pull request by joenyzio**
Moved notion to docs

### CODE REVIEW

**Comment by viral-sangani** [comment]
@joenyzio  Added some pages and made some changes. Can you please review this?

**Comment by ericnakagawa** [comment]
Fix typo "Upto" to "Up to" @viral-sangani

**Comment by ericnakagawa** [comment]
Add a section requiring adding front-matter at top of markdown file.

**Review by nestorbonilla — APPROVED** [review]
LGTM

**Pull request merged**
