### PR TITLE
0xarthurxyz/fix canolli

### PR DESCRIPTION
**Pull request by 0xarthurxyz**
### Adds info and fixes typos regarding Cannoli Testnet:

Adds new disclaimer page at `docs.celo.org/network/cannoli/disclaimer`:

* [adds disclaimer for testnet](https://github.com/celo-org/docs/commit/7a5545581691fccba0da75be80becb735cd12e8b)

Modifies network page at `docs.celo.org/network`:

* [adds `chainId` for cannoli](https://github.com/celo-org/docs/commit/863b44088a4e4f97571173886a31ba9e1dc955df)
* [adds admonition linking to canolli disclaimer](https://github.com/celo-org/docs/commit/7914bf022181453a2e1b7f182e747ac80219992a)
* [changes header to "Cannoli, the Ultragreen Testnet"](https://github.com/celo-org/docs/commit/10f45d4216309c3a590a5b7510322030edd561b1)
* [moves cannoli paragraph below alfajores and baklava](https://github.com/celo-org/docs/commit/5513416d63235ac68e60710d43b213e0b285a857) 
* [fixes cannoli faucet URL and hyperlink formatting](https://github.com/celo-org/docs/commit/badab7954605438f5cb491ab375b990ebb197959)
* [adds links to CIP52](https://github.com/celo-org/docs/commit/3a6b84094b97c81494ec48ba6ccd2366e8e2c13c)

Modifies Forno page at `docs.celo.org/network/node/forno`:

* [adds URL for canolli forno RPC provider](https://github.com/celo-org/docs/commit/8f099adbba5e55ff6b250f22db63bb6227016377)

### CODE REVIEW

**Comment by 0xarthurxyz** [comment]
Checks failed because I forgot to edit sidebar and had a typo in folder name

**Comment by 0xarthurxyz** [comment]
Some checks are still failing for reasons I don’t understand.
I can’t inspect the logs because the Netlify link doesn’t work for me (see screenshot).

image

**Comment by 0xarthurxyz** [comment]
### Update

The docs build fine locally.

It turns out the build is failing because there are too many files and the build times out. 
That means the Github checks are not failing because of changes I made above.

@viral-sangani can build locally and deploy using Netlify CLI.

**Review by joenyzio — APPROVED** [review]
LGTM!

**Pull request merged**
