### PR TITLE
feat: Cookbook Onboard (AI Assistant & Playground)

### LINKED ISSUE #1386: Feature Proposal: Cookbook Onboard (AI Assistant & Playground)
Preview link: https://celo-docs-cookbook.vercel.app/

## Ask Cookbook AI Assistant
Cookbook's Ask Cookbook AI assistant and co-pilot is trained on all existing Celo resources (source code, docs website, etc.) and is available as a standalone modal, embeddable as a button on any page (recommended for technical docs). It answers developer questions about using Celo, acting as an enhanced and streamlined technical documentation search tool as well as a Solidity language coding co-pilot.

Ask Cookbook AI can also access context from thousands of data sources indexed by Cookbook.dev in addition to Celo-specific data sources, providing the best blockchain developer-focused answers of any chatbot on the market. Cookbook will assist in the tuning and calibration of the AI assistant to ensure the highest answer quality.

image

## Cookbook Onboard Playground
The Cookbook Onboard Playground embeds a Solidity IDE with smart contract templates displayed alongside the Ask Cookbook AI Assistant.

Developers can search for and deploy Cookbook’s entire smart contract library from your technical documentation.

Features:
- Deploy smart contracts or entire protocols to Celo without leaving Celo's technical docs
- Acts as a free, no-code or low-code token and NFT launchpad
- Save source code as a Foundry, Hardhat, or Scaffold project or export it to Remix or Chain IDE in one click

image

### PR DESCRIPTION
**Pull request by ClockRide**
Resolves #1386

### CODE REVIEW

**Comment by therealharpaljadeja** [comment]
Do we have to pay for this service? 

If yes, please provide pricing plans. If no, please provide details on any limits (like no. of queries etc...)

Can you also please explain if the chatbot will have information about any new pages we add to the docs automatically or is there a process for the same?

**Comment by ClockRide** [comment]
> Thank you for the initiative!
> 
> Does Celo need to pay for this service?
> 
> If yes, please provide pricing plans. If no, please provide details on any limits (like no. of queries etc...)
> 
> Can you also please explain if the chatbot will have information about any new pages we add to the docs automatically or is there a process for the same?

Thank you for getting back to us! Right now, we're focused on growth and helping blockchains like Celo reduce developer onboarding friction within their ecosystems. Our goal is to enhance the effectiveness of our developer relations team, which is why we haven't set any pricing plans or limits for this version of Cookbook Onboard.

While some blockchain networks choose to support Cookbook’s free initiatives, such as this version of Cookbook Onboard, through token grants, there's no obligation for them to do so for us to make it available.

Regarding data population, we provide your team with access to our CMS, where you can configure the resources the bot uses to reply. By default, they are updated every 24 hours, but you can also refresh them manually when necessary :)

**Comment by ClockRide** [comment]
@therealharpaljadeja, are there any other questions or concerns we can address to get this merged? :)

**Review by sodofi — APPROVED** [review]
Reviewed IRL with michael

**Comment by therealharpaljadeja** [comment]
@ClockRide a secret exposed in `theme/Navbar/index.js` is it fine?

https://github.com/celo-org/docs/pull/1387/checks?check_run_id=28141879962

**Comment by ClockRide** [comment]
> @ClockRide a secret exposed in `theme/Navbar/index.js` is it fine?
> 
> 
> 
> https://github.com/celo-org/docs/pull/1387/checks?check_run_id=28141879962

Yep!

**Pull request merged**
